#!/usr/bin/with-contenv bash

if [ -d /app/www/public-tmp ]; then
    echo "New container detected. Setting up app folder and fixing permissions."
    mv /app/www/public-tmp /app/www/public
    chown -R abc:abc /app
fi

# set default values for variables
PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-512M}
MAX_UPLOAD=${MAX_UPLOAD:-5000}
PHP_MAX_FILE_UPLOAD=${PHP_MAX_FILE_UPLOAD:-200}
USABLE_MAX_UPLOAD=${MAX_UPLOAD//[!0-9]/}

# create our folders
mkdir -p \
    /config/projectsend \
    /data/projectsend

# configure php
sed -i \
    -e "s#;*memory_limit =.*#memory_limit = ${PHP_MEMORY_LIMIT}#i" \
    -e "s#;*upload_max_filesize =.*#upload_max_filesize = ${USABLE_MAX_UPLOAD}M#i" \
    -e "s#;*max_file_uploads =.*#max_file_uploads = ${PHP_MAX_FILE_UPLOAD}#i" \
    -e "s#;*post_max_size =.*#post_max_size = ${USABLE_MAX_UPLOAD}M#i" \
    -e "s#;*cgi.fix_pathinfo=.*#cgi.fix_pathinfo= 0#i" \
        /etc/php8/php.ini

# copy config
PREV_DIR=$(pwd)

cd /defaults/upload || exit 1
shopt -s globstar nullglob
shopt -s dotglob
    for i in *
    do
        if [ ! -e "/data/projectsend/${i}" ] ; then
        cp -R "${i}" "/data/projectsend/${i}"
        chown abc:abc "/data/projectsend/${i}"
        fi
    done

shopt -u globstar nullglob
shopt -u dotglob

cd "${PREV_DIR}" || exit 1

# create symlinks
if [[ ! -L /app/www/public/upload ]]; then
    ln -sf /data/projectsend /app/www/public/upload
fi

if [[ -f /app/www/public/includes/sys.config.php ]]; then
    rm /app/www/public/includes/sys.config.php
fi
if [[ ! -L /app/www/public/includes/sys.config.php ]]; then
    ln -sf /config/projectsend/sys.config.php /app/www/public/includes/sys.config.php
fi

# permissions
echo "Fixing app data permissions."
chown abc:abc \
    /data/projectsend
chown -R abc:abc \
    /config
