#!/usr/bin/with-contenv bash

# create our folders
mkdir -p \
	/config/projectsend/images \
	/data/projectsend \
	/var/run/apache2

PREV_DIR=$(pwd)

cd /defaults/upload || exit
shopt -s globstar nullglob
shopt -s dotglob
	for i in *
	do
		if [ ! -e "/data/projectsend/${i}" ] ; then
		cp -R "${i}" "/data/projectsend/${i}"
		chown abc:abc "/data/projectsend/${i}"
		fi
	done

cd /defaults/custom || exit
	for i in *
	do
		if [ ! -e "/config/projectsend/images/${i}" ] ; then
		cp -R "${i}" "/config/projectsend/images/${i}"
		chown abc:abc "/config/projectsend/images/${i}"
		fi
	done
shopt -u globstar nullglob
shopt -u dotglob

cd "${PREV_DIR}" || exit

# create symlinks
[[ ! -L /var/www/localhost/htdocs/upload ]] && \
	ln -sf /data/projectsend /var/www/localhost/htdocs/upload
[[ ! -L /var/www/localhost/htdocs/img/custom ]] && \
	ln -sf /config/projectsend/images /var/www/localhost/htdocs/img/custom

[[ -f /var/www/localhost/htdocs/includes/sys.config.php ]] && \
	rm /var/www/localhost/htdocs/includes/sys.config.php
[[ ! -L /var/www/localhost/htdocs/includes/sys.config.php ]] && \
	ln -sf /config/projectsend/sys.config.php \
	/var/www/localhost/htdocs/includes/sys.config.php

# permissions
chown abc:abc \
	/data \
	/data/projectsend

	chown -R abc:abc \
	/config \
	/var/run/apache2 \
	/var/www/localhost/htdocs
