#!/usr/bin/with-contenv bash

# create our folders
mkdir -p \
	/config/projectsend/images \
	/data/projectsend

# copy config files
[[ ! -e /config/projectsend/sys.config.php ]] && \
	cp /defaults/config.php /config/projectsend/sys.config.php

PREV_DIR=$(pwd)

cd /defaults/upload || exit
shopt -s globstar nullglob
shopt -s dotglob
	for i in *
	do
		if [ ! -e "/data/projectsend/${i}" ] ; then
		cp -R "${i}" "/data/projectsend/${i}"
		chown abc:abc "/data/projectsend/${i}"
		fi
	done

cd /defaults/custom || exit
	for i in *
	do
		if [ ! -e "/config/projectsend/images/${i}" ] ; then
		cp -R "${i}" "/config/projectsend/images/${i}"
		chown abc:abc "/config/projectsend/images/${i}"
		fi
	done
shopt -u globstar nullglob
shopt -u dotglob

cd "${PREV_DIR}" || exit

# create symlinks
[[ ! -L /usr/share/webapps/projectsend/upload ]] && \
	ln -sf /data/projectsend /usr/share/webapps/projectsend/upload
[[ ! -L /usr/share/webapps/projectsend/img/custom ]] && \
	ln -sf /config/projectsend/images /usr/share/webapps/projectsend/img/custom

[[ -f /usr/share/webapps/projectsend/includes/sys.config.php ]] && \
	rm /usr/share/webapps/projectsend/includes/sys.config.php
[[ ! -L /usr/share/webapps/projectsend/includes/sys.config.php ]] && \
	ln -sf /config/projectsend/sys.config.php \
	/usr/share/webapps/projectsend/includes/sys.config.php

# permissions
chown abc:abc \
	/data \
	/data/projectsend

	chown -R abc:abc \
	/config \
	/usr/share/webapps/projectsend/includes \
	/usr/share/webapps/projectsend/upload \
	/usr/share/webapps/projectsend/img/custom
